export const foodItemMap: Record<string, string> = {
  adhirasam: "Adhirasam",
  aloo_gobi: "Aloo Gobi",
  aloo_matar: "Aloo Matar",
  aloo_methi: "Aloo Methi",
  aloo_shimla_mirch: "Aloo Shimla Mirch",
  aloo_tikki: "Aloo Tikki",
  anarsa: "Anarsa",
  ariselu: "Ariselu",
  bandar_laddu: "Bandar Laddu",
  basundi: "Basundi",
  bhatura: "Bhatura",
  bhindi_masala: "Bhindi Masala",
  biryani: "Biryani",
  boondi: "Boondi",
  butter_chicken: "Butter Chicken",
  chak_hao_kheer: "Chak Hao Kheer",
  cham_cham: "Cham Cham",
  chana_masala: "Chana Masala",
  chapati: "Chapati",
  chhena_kheeri: "Chhena Kheeri",
  chicken_razala: "Chicken Razala",
  chicken_tikka: "Chicken Tikka",
  chicken_tikka_masala: "Chicken Tikka Masala",
  chikki: "Chikki",
  daal_baati_churma: "Daal Baati Churma",
  daal_puri: "Daal Puri",
  dal_makhani: "Dal Makhani",
  dal_tadka: "Dal Tadka",
  dharwad_pedha: "Dharwad Pedha",
  doodhpak: "Doodhpak",
  double_ka_meetha: "Double Ka Meetha",
  dum_aloo: "Dum Aloo",
  gajar_ka_halwa: "Gajar Ka Halwa",
  gavvalu: "Gavvalu",
  ghevar: "Ghevar",
  gulab_jamun: "Gulab Jamun",
  imarti: "Imarti",
  jalebi: "Jalebi",
  kachori: "Kachori",
  kadai_paneer: "Kadai Paneer",
  kadhi_pakoda: "Kadhi Pakoda",
  kajjikaya: "Kajjikaya",
  kakinada_khaja: "Kakinada Khaja",
  kalakand: "Kalakand",
  karela_bharta: "Karela Bharta",
  kofta: "Kofta",
  kuzhi_paniyaram: "Kuzhi Paniyaram",
  lassi: "Lassi",
  ledikeni: "Ledikeni",
  litti_chokha: "Litti Chokha",
  lyangcha: "Lyangcha",
  maach_jhol: "Maach Jhol",
  makki_di_roti_sarson_da_saag: "Makki Di Roti Sarson Da Saag",
  malapua: "Malapua",
  misi_roti: "Misi Roti",
  misti_doi: "Misti Doi",
  modak: "Modak",
  mysore_pak: "Mysore Pak",
  naan: "Naan",
  navrattan_korma: "Navrattan Korma",
  palak_paneer: "Palak Paneer",
  paneer_butter_masala: "Paneer Butter Masala",
  phirni: "Phirni",
  pithe: "Pithe",
  poha: "Poha",
  poornalu: "Poornalu",
  pootharekulu: "Pootharekulu",
  qubani_ka_meetha: "Qubani Ka Meetha",
  rabri: "Rabri",
  rasgulla: "Rasgulla",
  ras_malai: "Ras Malai",
  sandesh: "Sandesh",
  shankarpali: "Shankarpali",
  sheera: "Sheera",
  sheer_korma: "Sheer Korma",
  shrikhand: "Shrikhand",
  sohan_halwa: "Sohan Halwa",
  sohan_papdi: "Sohan Papdi",
  sutar_feni: "Sutar Feni",
  unni_appam: "Unni Appam",
};

// Helper function to get formatted food name
export const getFormattedFoodName = (foodKey: string): string => {
  return foodItemMap[foodKey] || foodKey;
};
