export const healthConditionMap: Record<string, string> = {
  diabetes: "Diabetes",
  diabetes_type_1: "Type 1 Diabetes",
  diabetes_type_2: "Type 2 Diabetes",
  heart_disease: "Heart Disease",
  hypertension: "Hypertension",
  obesity: "Obesity",
  kidney_disease: "Kidney Disease",
  liver_disease: "Liver Disease",
  high_cholesterol: "High Cholesterol",
  celiac_disease: "Celiac Disease",
  lactose_intolerance: "Lactose Intolerance",
  gout: "Gout",
  ibs: "Irritable Bowel Syndrome (IBS)",
  crohns_disease: "Crohn's Disease",
  ulcerative_colitis: "Ulcerative Colitis",
  gastritis: "Gastritis",
  acid_reflux: "Acid Reflux",
  fatty_liver: "Fatty Liver Disease",
  hypothyroidism: "Hypothyroidism",
  hyperthyroidism: "Hyperthyroidism",
  anemia: "Anemia",
  osteoporosis: "Osteoporosis",
  arthritis: "Arthritis",
  migraine: "Migraine",
  anxiety: "Anxiety",
  depression: "Depression",
  insomnia: "Insomnia",
  cancer: "Cancer",
  stroke: "Stroke",
  copd: "COPD",
  asthma: "Asthma",
  allergies: "Allergies",
  food_allergies: "Food Allergies",
  pcos: "PCOS",
  endometriosis: "Endometriosis",
  pregnancy: "Pregnancy",
  breastfeeding: "Breastfeeding",
  menopause: "Menopause",
  eating_disorder: "Eating Disorder",
  malnutrition: "Malnutrition",
  vitamin_deficiency: "Vitamin Deficiency",
  mineral_deficiency: "Mineral Deficiency",
  metabolic_syndrome: "Metabolic Syndrome",
  insulin_resistance: "Insulin Resistance",
  prediabetes: "Prediabetes",
  gestational_diabetes: "Gestational Diabetes",
  autoimmune_disease: "Autoimmune Disease",
  inflammatory_bowel_disease: "Inflammatory Bowel Disease",
  peptic_ulcer: "Peptic Ulcer",
  gallstones: "Gallstones",
  pancreatitis: "Pancreatitis",
  diverticulitis: "Diverticulitis",
  constipation: "Constipation",
  diarrhea: "Diarrhea",
  nausea: "Nausea",
  vomiting: "Vomiting",
  bloating: "Bloating",
  gas: "Gas",
  heartburn: "Heartburn",
  indigestion: "Indigestion",
  food_poisoning: "Food Poisoning",
  malabsorption: "Malabsorption",
  lactose_malabsorption: "Lactose Malabsorption",
  fructose_malabsorption: "Fructose Malabsorption",
  sorbitol_intolerance: "Sorbitol Intolerance",
  histamine_intolerance: "Histamine Intolerance",
  salicylate_sensitivity: "Salicylate Sensitivity",
  msg_sensitivity: "MSG Sensitivity",
  sulfite_sensitivity: "Sulfite Sensitivity",
  gluten_sensitivity: "Gluten Sensitivity",
  wheat_allergy: "Wheat Allergy",
  egg_allergy: "Egg Allergy",
  milk_allergy: "Milk Allergy",
  soy_allergy: "Soy Allergy",
  nut_allergy: "Nut Allergy",
  peanut_allergy: "Peanut Allergy",
  shellfish_allergy: "Shellfish Allergy",
  fish_allergy: "Fish Allergy",
  sesame_allergy: "Sesame Allergy",
  seed_allergy: "Seed Allergy",
  spice_allergy: "Spice Allergy",
  fruit_allergy: "Fruit Allergy",
  vegetable_allergy: "Vegetable Allergy",
  meat_allergy: "Meat Allergy",
  alcohol_intolerance: "Alcohol Intolerance",
  caffeine_sensitivity: "Caffeine Sensitivity",
  artificial_sweetener_sensitivity: "Artificial Sweetener Sensitivity",
  preservative_sensitivity: "Preservative Sensitivity",
  colorant_sensitivity: "Colorant Sensitivity",
  flavoring_sensitivity: "Flavoring Sensitivity",
  none: "None",
};

export function getFormattedConditionName(condition: string): string {
  return healthConditionMap[condition] || condition;
}
